### ISSUE TITLE
Migrate Optional Scope Modules (TypeScript 2) to DefinitelyTyped/@types

### ISSUE THREAD

**Issue by tomwanzek** [tomwanzek/d3-v4-definitelytyped#105]
This issue tracks the high-level status of migrating the _Typescript 2_ definitions with tests to **DefinitelyTyped** (`types-2.0` branch) and their propagation to the **@types organization**.

| Module | DefinitelyTyped/types-2.0 | @types |
| --- | --- | --- |
| **d3-geo-projection** | _not started_ | _not started_ |
| **d3-hexbin** | _not started_ | _not started_ |
| **d3-hsv** | Current | Current |
| **d3-sankey** | _not started_ | _not started_ |
| **d3-scale-chromatic** | _[PR 11370](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11370)_ | _pending DT_ |
| **d3-selection-multi** | Current | Current |
| **d3-tile** | _not started_ | _not started_ |

**Comment by tomwanzek** [comment]
@Ledragon your definitions for d3-scale-chromatic have been merged into DT/types-2.0 and are up and running with working version number on npm @types!

Thanks for all the contributions!!!

**Comment by Ledragon** [comment]
weehee :tada: 
Most welcome!
