### ISSUE TITLE
Does d3-ease definition need to be updated?

### ISSUE THREAD

**Issue by billdwhite** [tomwanzek/d3-v4-definitelytyped#132]
I am using a transition with an easing function in d3 in my Angular 2 typescript application.  The following line of code, which I believe is valid, is generating errors when the typescript validation runs.
```
...
mySelection.enter().transition().ease(d3.easeElasticIn.amplitude(4).period(3)).attr("x", 100);
...
```

I get this error in the angular-cli 'ng build' process:

`Property 'amplitude' does not exist on type '(normalizedTime: number) => number'`

Looking at the d3-ease/index.d.ts file, I see this:

```
...
export function easeElasticIn(normalizedTime: number): number;
...
```

So is the d3-ease typescript definition just wrong?  Looking at the [d3 source code](https://github.com/d3/d3-ease/blob/master/src/elastic.js), it appears so but maybe I'm just not understanding something?

**Comment by tomwanzek** [comment]
@billdwhite thanks for reporting. I am closing this issue in favor of the newly opened [DT issue 13767](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13767)

**Comment by billdwhite** [comment]
Thanks!!!
