### ISSUE TITLE
Selection to transition

### ISSUE THREAD

**Issue by ocombe** [tomwanzek/d3-v4-definitelytyped#34]
d3-selection and d3-transition both export `Selection`, the one from d3-transition extends the one from d3-selection with the addition of interrupt & transition, but it doesn't work in all use cases.
Let's say that I have a selection:

```
let element: Selection = d3.select('div');
```

now if this is a `Selection` from d3-selection, I cannot call `.transition()` on it, so I change this to a `Selection` from d3-transition, but then if I call `style()` before `transition()` then it won't work because the method `style()` returns a `Selection` from d3-selection, not a `Selection` from d3-transition, and it doesn't have `transition()` ...

To make it work I have to declare my `element` as a `Transition`, but it isn't one until I call `transition()`, right ? I find this really weird.

**Comment by tomwanzek** [comment]
@ocombe Can you please let me know, if you still experience any issue as initially outlined above. I closed this issue, as the d3-transition and d3-selection tests in the repo perform as expected. (Now that I pushed all the d3-transition tests).

There is a minor quirk related to what I had previously referred to as 'module augmentation bleed' in the d3-selection tests. In that, the `Selection` interface is augmented by the d3-transition imports in other test files. Which in hindsight makes perfect sense. I just chased an edge case thought, wanting to test `Selection` without augmentation without narrowing the compilation context. Of little practical relevance to begin with... Just a figment of the repo design for staging purposes. Ah, good old having the cake and eating it.
