### ISSUE TITLE
Use of TimeInterval in axis ticks(...)

### ISSUE THREAD

**Issue by tomwanzek** [tomwanzek/d3-v4-definitelytyped#38]
The `ticks(...)` method of an axis with a `Date` based domain should ideally be typed as:

```
ticks(interval: TimeInterval, specifier?: string)
```

Here `TimeInterval` is an interface imported from the **d3-time** module. However, since the **d3-axis** module has no dependency on **d3-time**, this would create a definitions level dependency, which is unnecessary when time scales are not used for the axis.

Currently, there is a separate line with an `interval` argument, but this argument is typed as `any` to workaround. Commented out code with `TODO:` and `HACK:` comments indicate the alternatives in the **d3-axis** definitions file and the related test file.

The best choice may depend on the ultimate solution to issue #1.

**Comment by jnm2** [comment]
If importing d3-time.js is necessary to use the TimeInterval method, is there any way to have the TimeInterval method light up when d3-time is added? Is there a way for one d.ts to detect whether types from another d.ts are available?

If it's not necessary to import d3-time.js to use the TimeInterval method, is it possible to define TimeInterval both places if not already defined?

**Comment by tomwanzek** [comment]
To my knowledge there is no way to create conditional imports/exports as part of writing definition files, let alone adding/removing related method signatures from an interface. Should there be a pattern, I would be curious to know.

The **current workaround** would be to manually change the commenting in/out for the related `import` and `ticks(...)` signatures, whenever your project uses d3-time.

The scenario for d3-axis is different from d3-scale. The latter has a proper dependency on d3-time anyway, so importing the interfaces becomes a non-issue.

Putting a module augmentation of the `Axis` interface into the d3-time module definitions also seems counterproductive. It would introduce a coupling between the modules that does not exist with that directionality in the underlying source modules.

I am currently holding off on this question for the following reason. As you are probably aware, the new D3 modules can be used in two ways: (a) as imported modules and (b) in a vanilla script using the `d3` global.

The current definitions are written as proper modules, one line that is currently missing from the individual modules definition files is `export as namespace d3;` This makes the definitions usable as UMD module definitions for module import and vanilla scenarios. However, as each D3 module exports to the _same_ global identifier, in turn augmenting it, there is a _multiple declaration conflict_.

I am going to flag this as a separate issue which still needs to be explored/resolved.

But for this reason simply duplicating the interface would likely create more issues/confusion than it addresses. When I have a spare second, I might look into the possibility of creating a stripped down interface (similar to `AxisScale`), but I will need to asses how minimal this could be. I had to focus on other priorities in the meantime.

BTW, currently, the aforementioned UMD structure is the approach taken in the [definitions file for the standard D3 bundle](https://github.com/tomwanzek/d3-v4-definitelytyped/blob/master/src/d3/index.d.ts). It re-exports the constituent D3 modules and also creates the global `d3`. Both are usable, depending on the use case at hand.

**Comment by jnm2** [comment]
I guess part of the question is, what happens if you call the TimeInterval method in plain JavaScript without d3-time? If that succeeds at runtime, I would also expect the TypeScript TimeInterval method definition to be available without d3-time's type definitions.

If this is the case, I see a legitimate place for a d3 core d.ts because it's necessary for you to unify something which was duplicated in the underlying libraries but still coupled. Or some d.ts  which would be shared by both d3-axis and d3-time.

**Comment by tomwanzek** [comment]
Now that a lot of the higher priority items were resolved. I circled back to the source code of d3-axis and d3-scale. It seems the minimal interface added in #70 addresses the issue as flexibly as possible. :tada:
