### ISSUE TITLE
Ambiguity in `data` key function argument

### ISSUE THREAD

**Issue by zbjornson** [tomwanzek/d3-v4-definitelytyped#54]
In this:

``` ts
d3.select("p")
    .data([0, 1, 2], function (d) { return d.toString(); });
```

`d` is inferred as `{} | number`, which I _think_ is an unnecessary ambiguity.

Changing this:

``` ts
    data<NewDatum>(
        data: Array<NewDatum>,
        key?: (this: GElement | PElement, datum?: Datum | NewDatum, index?: number, group?: Array<GElement | PElement> | ArrayLike<GElement | PElement>) => string
    ): Selection<GElement, NewDatum, PElement, PDatum>;
```

to this:

``` ts
    data<NewDatum>(
        data: Array<NewDatum>,
        key?: (this: GElement | PElement, datum?: NewDatum, index?: number, group?: Array<GElement | PElement> | ArrayLike<GElement | PElement>) => string
    ): Selection<GElement, NewDatum, PElement, PDatum>;
```

resolves the ambiguity, but I'm not sure if there's a use case I'm missing where the original Datum and not the NewDatum would be passed to the key fn.

**Comment by tomwanzek** [comment]
I'll have to look at it again tomorrow, I thought I saw something in the source code, where the key function was invoked in two different spots with slightly different arguments.

**Comment by zbjornson** [comment]
Ah you're right, my bad. 

> This key function is evaluated for each selected element, in order, being passed the current datum (d), the current index (i), and the current group (nodes), with this as the current DOM element. The key function is then also evaluated for each new datum in data, being passed the current datum (d), the current index (i), and the group’s new data, with this as the group’s parent DOM element.
