### ISSUE TITLE
Chore: Implement editorconfig comparable to DefinitelyTyped and Clean-Up Files

### ISSUE THREAD

**Issue by tomwanzek** [tomwanzek/d3-v4-definitelytyped#65]
Given the ultimate target repo DefinitelyTyped, should implement the editorconfig used there.
Clean-up files in this repo to match (i.e. indentation, trailing white-space, final empty line.)

**Comment by tomwanzek** [comment]
Done. Thanks @Ledragon for the input.

**Comment by Ledragon** [comment]
Most welcome!
