### ISSUE TITLE
d3-force: force.initialize should be optional

### ISSUE THREAD

**Issue by spiffytech** [tomwanzek/d3-v4-definitelytyped#94]
According to the [d3-force README](https://github.com/d3/d3-force#forces), `force.initialize` is optional. The typings should accept a bare function as the `force` parameter for `force.force(name, force)`.

**Comment by tomwanzek** [comment]
Thanks. You are indeed correct. I will make the corresponding fix with a PR I am getting ready with a minor change the the `.force()` method.
