### ISSUE TITLE
[Request] - Instructions to try out the typings

### ISSUE THREAD

**Issue by olivierboucher** [tomwanzek/d3-v4-definitelytyped#97]
Hi Tom,

Sorry to file out this issue but I couldn't find your email anywhere. I just wanted to know what would be the easiest way to try out the typings. I'm already using typescript@next and I wondered if simply copy pasting the src would do it.

Thanks

**Comment by tomwanzek** [comment]
Hi  Olivier,

If you have a look at the Module-Level Status section of the README, you will find an updated status of which module definitions have been migrated in an initial version to the `DefinitelyTyped/types-2.0` branch and propagated to the npm @types organization. Where in initial version is available on @types, you can simply install the definition with e.g.

```
npm install @types/d3-selection --save
```

When you install them this way, TS2 will resolve the definitions correctly without any need for **typings** to be used.

This repo already reflects a few improvements, which I will in short order push as follow-ups through a DefinitelyTyped PR to these initial files, which will eventually also propagate to @types.

Hope this clarifies. Where there are known definition specific issues, you can check in this repo, until the migration is completed.

**Comment by olivierboucher** [comment]
Thanks a lot !
